apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
data:
  encrypted.property: ENC(BtpxHD/Wji4QjwvmDyN68iyqHgErizN2lIkt5KwCg2GIx5SUUlFs/G0hBJ3395oOmObbmUhp/cVU2AjlOuFCSr/3efTvn3CiXd15p1WXchXCUsBpRnKh3voo52pHIRg0)
