---
applications:
- name: leap-demo-spring-appapp
  host: leap-test-uat
  memory: 512M
  path: leap-demo-spring-appapp-war.war
  buildpack: java_buildpack_offline_v3_12
  health-check-type: process
  maximum_health_check_timeout: 180
  env:
      SPRING_PROFILES_ACTIVE: dev